version: "3.8"
services:
  aiidalab:
    build: .
    ports:
      - ${AIIDALAB_PORT}:8888
    environment:
      - JUPYTER_TOKEN
    volumes:
      - ~/aiidalab:/home/aiida
    secrets:
      - ssh_key
secrets:
  ssh_key:
    file: ~/.ssh/id_rsa
