---
openapi: 3.0.0

info:
    title: AiiDAlab QEApp
    description: OpenAPI Specification of the MarketPlace AiiDAlab Quantum ESPRESSO deployment
    version: 0.1.0
    x-application-name: AiiDAlab QeApp
    x-oauth-client:
        client-id:
        scopes:
            - email
            - openid
            - profile
        callback: https://aiidalab.materials-marketplace.eu/hub/oauth_callback
    x-external-hostname: https://aiidalab.materials-marketplace.eu
    x-contacts:
        - jusong.yu@psi.ch
    x-products:
        - name: AiiDAlab QE app
          productId:
servers:
    - url: https://aiidalab.materials-marketplace.eu

paths:


    /hub/user-redirect/apps/apps/quantum-espresso/qe.ipynb:
        get:
            description: QEApp
            operationId: frontend
            security:
                - bearerAuth: []
            responses:
                '200':
                    description: Success
                '404':
                    description: Page not found

    /hub/health:
        get:
            description: To check if an application is alive
            operationId: heartbeat
            security: []
            responses:
                '200':
                    description: Success
                '404':
                    description: Not found

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
