openapi: 3.0.0
 
info:
  title: API description of a Marketplace Application
  description: 'OpenAPI Specification of the Application registration API'
  version: '0.1.0'
  x-application-name: AiiDA-lab-QEapp
  x-application-id: 2c7c68ab-84b3-45e6-b3d8-fe87f64937e3
  x-mp-api: http://marketplace.org/ontology/v1_0_0/api_spec
  x-external-hostname: https://materials-marketplace.aiidalab.net/
  x-image: https://raw.githubusercontent.com/aiidalab/aiidalab-widgets-base/master/miscellaneous/logos/aiidalab.png
  x-products:
    - name: QE App
      productId: 87f0189b-00b7-4ae3-a017-8d85e766d3d5
servers:
  - url: https://materials-marketplace.aiidalab.net/

paths:
# Administrative paths
  /hub/user-redirect/apps/apps/quantum-espresso/qe.ipynb:
    get:
      description: frontend path
      operationId: frontend
      responses:
        '200':
          description: Success
        '404':
          description: Page not found

  /hub/health:
    get:
      description: To check if an application is alive
      operationId: heartbeat
      responses:
        '200':
          description: Success
        '404':
          description: Not found
 
components:
  securitySchemes:
    AuthHeader:        
      type: apiKey
      in: header       
      name: Authorization  
