---
openapi: 3.0.0

info:
    title: AiiDAlab QE App
    description: OpenAPI Specification of the MarketPlace AiiDAlab deployment
    version: 0.2.0
    x-application-name: AiiDAlab QE App
    x-external-hostname: https://materials-marketplace.aiidalab.net
    x-image: https://raw.githubusercontent.com/aiidalab/aiidalab-qe/v20.12.0/miscellaneous/logos/QE.jpg
    x-contacts:
        - simon.adorf@epfl.ch
    x-products:
        - name: AiiDAlab QE app
          productId:
servers:
    - url: https://materials-marketplace.aiidalab.net

paths:

    ? /user-redirect/apps/apps/home/open_app.ipynb?app=quantum-espresso&redirect=user-redirect/apps/apps/quantum-espresso/qe.ipynb
    :   description: QE App
        operationId: frontend
        security:
            - bearerAuth: []
        responses:
            '200':
                description: Success
            '404':
                description: Page not found

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
